- name: delate apcahe/http and remove http files
  hosts: "{{ hosts }}"
  become: yes

  tasks:
    - name: shutdown
      shell: init 0 

# ansible-playbook OFF_work_linux.yml --extra-var "hosts=linux_work"
# ansible-playbook OFF_work_linux.yml --extra-var "hosts=linux_home"