---
- name: Include exemple
  hosts: "{{ MYHOSTS }}"
  become: yes

  vars:
    mytext: "Test text fom Zak"
  
  tasks:
  - name: Ping test
    ping:

  - name: Create Folders
    include_tasks: playbook10_creat_fold.yml

  - name: Create files
    include_tasks: playbook10_creat_file.yml 
    vars:
      mytext: var from include