---
# tasks file for deply_apache_web
- name: Check and print destribution name
  debug: var=ansible_os_family
#RHD
- name: Block for RedHat
  block:

   - name: install apache webserver RedHat
     yum: name=httpd state=latest
     
   - name: Start and enable apache on the boot RedHat family os
     service: name=httpd state=started enabled=yes
     
  #  - name: Iptables enable port 80
  #    iptables:
  #      comment: Allow 80 port HTTP   #    shell: iptables -I INPUT 1 -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT
  #      chain_management: true        #Разрешаем управление iptables
  #      state: present                #Если правила нет то создать если есть то ничего не делать
  #      action: insert                #По умолчанию append - добавляет в конец
  #      chain: INPUT
  #      ctstate: NEW
  #      protocol: tcp
  #      destination_ports: 80
  #      jump: ACCEPT

  #  - name: IP tables save
  #    shell: iptables-save > /etc/sysconfig/iptables

  #  - name: IP tables restore on pre-up
  #    shell: echo -e "#!/bin/bash \niptables-restore < /etc/sysconfig/iptables" > {{sh_ipt_pwd}} && chmod +x {{sh_ipt_pwd}}

  when: ansible_os_family == "RedHat"
#DEB     
- name: Block for Debian
  block:    
   - name: install apache webserver RedHat
     apt: name=apache2 state=latest

   - name: Start and enable apache on the boot Debian family os
     service: name=apache2 state=started enabled=yes 

  when: ansible_os_family == "Debian"

# Generate index.html
- name: Generate INDEX.html from template j2
  template: src=index.j2 dest={{ destin_folder }}/index.html mode=555
  notify: 
    - Restart Apache RedHat
    - Restart Apache Debian

#Копирование содержимого дирриктории
- name: cp files for websites
  copy: src={{ item }} dest={{ destin_folder }} mode=555
  with_fileglob: "*.*"
  notify: 
    - Restart Apache RedHat
    - Restart Apache Debian